INSERT INTO viewbabsatu (
            id,
            nama_berkas,
            judul_berkas,
            nama_pt,
            alamat_pt,
            izinop_text,
            izinop_file, 
            statakreinst_text,
            statakreinst_file,
            namaptmitra,
            alamatptmitra,
            negaramitra,
            izinopmitra_text,
            izinopmitra_file,
            statakreinstmitra_text,
            statakreinstmitra_file,
            peringinter,
            namaprodipt_select,
            namaprodimitra_text,
            akreprodpt_select,
            akreprodmitra_text,
            sk_akprodpt_file,
            sk_akprodmitra_file,
            izopeprodipt_file,
            izopeprodimitra_file,
            proposalusul_file,
            created_at,
            updated_at 
    )
VALUES (
        '1',
        '2305140001.1',
        'Gelar Ganda(Double Degree) Universitas Halu Oleo S2 Peternakan dengan PT.ABC Peternakan ITB',
        'Universitas Halu Oleo',
        'Kampus Bumi Tridharma Anduonohu, Jalan.H.E. Mokodompit, Kodya Kendari, Sulawesi, Kota Kendari, Prov.Sulawesi Tenggara',
        'KEPUTUSAN DIREKTUR JENDERAL PENDIDIKAN TINGGI NOMOR 4315 TAHUN 2018 TENTANG PETUNJUK TEKNIS IZIN PENDIRIAN, PERUBAHAN DAN PENCABUTAN IZIN PERGURUAN TINGGI',
        'izinop_file/sk-izinpt1.pdf',
        'B (Baik Sekali)',
        'statakreinst_file/SK-Akreditasipt1.pdf',
        'Institut Teknologi Bandung',
        'Kampus Jatinangor Jl. Let. Jend. Purn. Dr. (HC) Mashudi No.1, Kec.Jatinangor, Kab.Sumedang, Prov.Jawa Barat',
        'Indonesia',
        'KEPUTUSAN DIREKTUR JENDERAL PENDIDIKAN TINGGI NOMOR 3057 TAHUN 2018 TENTANG PETUNJUK TEKNIS IZIN PENDIRIAN, PERUBAHAN DAN PENCABUTAN IZIN PERGURUAN TINGGI',
        'izinopmitra_file/sk-izinpt2.pdf',
        'A (Unggul)',
        'statakreinstmitra_file/SK-Akreditasipt2.pdf',
        '235 di dunia berdasarkan QS World',
        'S2 Peternakan',
        'S2 Teknik Elektro',
        'B (Baik Sekali)',
        'A (Unggul)',
        'sk_akprodpt_file/SK-Akreditasiprodi1.pdf',
        'sk_akprodmitra_file/SK-Akreditasiprodi2.pdf',
        'izopeprodipt_file/SK-Izinprodi1.pdf',
        'izopeprodimitra_file/SK-Izinprodi2.pdf',
        'proposalusul_file/proposal.pdf',
        '',
        ''    
    );
